apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opticon-hub.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.hub_ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opticon-hub
            port:
              number: 80  # Dies ist der Service-Port, der zum Service weiterleitet
