apiVersion: v1
kind: Service
metadata:
  name: opticon-hub
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "opticon-hub.name" . }}
spec:
  type: {{ .Values.hub_service.type }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{ .Values.hub_service.app_port }}
  selector:
    app: {{ include "opticon-hub.name" . }}