namespace: streamlit-test

hub:
  image: opticon-hub
  tag: v0.1.0
  pullPolicy: IfNotPresent

operator:
  image: opticon-operator
  tag: v0.1.0

git_sync:
  image: registry.k8s.io/git-sync
  tag: v3.1.3

hub_service:
  type: ClusterIP
  app_port: 8000

hub_ingress:
  host: opticon-hub.mini.kube

streamlit_ingress:
  base_dns: mini.kube
  suffix: opticon

auth_config:
  KEYCLOAK_CLIENT_ID: streamlit
  KEYCLOAK_CLIENT_SECRET: VkdgVRHLu9eQfmxPYGbvmpXNVezSqxZP
  KEYCLOAK_AUTHORITY: http://192.168.59.1:8089/realms/test